sudo: required

language: go

go:
  - 1.6

services:
  - docker

before_install:
  - echo "$(git rev-parse --short HEAD)" >> .tag

install:
  - ./build.sh $(cat .tag)

script:
  - docker run --name dirigent-cli-build dirigent-cli:$(cat .tag)

after_success:
  - docker commit dirigent-cli-build quay.io/weitenghuang/dirigent-cli:$(cat .tag)
  - docker tag quay.io/weitenghuang/dirigent-cli:$(cat .tag) quay.io/weitenghuang/dirigent-cli:latest
  - docker login -e="." -u=$QUAY_USER -p=$QUAY_TOKEN quay.io
  - ([ "$TRAVIS_BRANCH" == "master" ] && docker push quay.io/weitenghuang/dirigent-cli)